INSERT INTO PRJ_DATA_DICT(ID, NAME, TEXT, VALUE, DESCRIPTION) VALUES (1, 'select1', 'Option 1', '1', '');
INSERT INTO PRJ_DATA_DICT(ID, NAME, TEXT, VALUE, DESCRIPTION) VALUES (2, 'select1', 'Option 2', '2', '');
INSERT INTO PRJ_DATA_DICT(ID, NAME, TEXT, VALUE, DESCRIPTION) VALUES (3, 'select1', 'Option 3', '3', '');
INSERT INTO PRJ_DATA_DICT(ID, NAME, TEXT, VALUE, DESCRIPTION) VALUES (4, 'select1', 'Option 4', '4', '');
INSERT INTO PRJ_DATA_DICT(ID, NAME, TEXT, VALUE, DESCRIPTION) VALUES (5, 'select1', 'Option 5', '5', '');