CREATE TABLE acl_sid (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL PRIMARY KEY, principal BOOLEAN NOT NULL, sid VARCHAR_IGNORECASE(100) NOT NULL, CONSTRAINT UN_ACL_SID_PRINCIPAL UNIQUE (sid, principal));

CREATE TABLE acl_class (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL PRIMARY KEY, class VARCHAR_IGNORECASE(100) NOT NULL, CONSTRAINT UN_ACL_CLASS UNIQUE (class));

CREATE TABLE acl_object_identity (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL PRIMARY KEY, object_id_class BIGINT NOT NULL, object_id_identity BIGINT NOT NULL, parent_object BIGINT, owner_sid BIGINT, entries_inheriting BOOLEAN NOT NULL, CONSTRAINT UN_ACL_CLASS_ID UNIQUE (object_id_class, object_id_identity), CONSTRAINT FK_ACL_OBJ_ID FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id), CONSTRAINT FK_ACL_CLASS FOREIGN KEY (object_id_class) REFERENCES acl_class (id), CONSTRAINT FK_ACL_SID FOREIGN KEY (owner_sid) REFERENCES acl_sid (id));

CREATE TABLE acl_entry (id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL PRIMARY KEY, acl_object_identity BIGINT  NOT NULL, ace_order INT NOT NULL, sid BIGINT  NOT NULL, mask INTEGER NOT NULL, granting BOOLEAN NOT NULL, audit_success BOOLEAN NOT NULL, audit_failure BOOLEAN NOT NULL, CONSTRAINT UK_ACL_OI_ORDER UNIQUE (acl_object_identity, ace_order), CONSTRAINT FK_ACL_ENTRY_OI FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity (id), CONSTRAINT FK_ACL_ENTRY_SID FOREIGN KEY (sid) REFERENCES acl_sid (id));

INSERT INTO SEC_ROLE (ID, PATH, ALIAS, DESCRIPTION) VALUES (1, '/USER', 'USER', 'USER');
INSERT INTO SEC_ROLE (ID, PATH, ALIAS, DESCRIPTION) VALUES (2, '/USER/ADMIN', 'ADMIN', 'ADMIN');

INSERT INTO PRJ_MENUITEM (ID, NAME, URL, MENU_GROUP, MENU_ITEM_GROUP) VALUES (1, 'PROJECT_DATA_DICT', '/project/dict', 'ADMINISTRATION', 'ENVIRONMENT');
INSERT INTO PRJ_MENUITEM (ID, NAME, URL, MENU_GROUP, MENU_ITEM_GROUP) VALUES (2, 'PROJECT_MENU_ITEM', '/project/menu', 'ADMINISTRATION', 'ENVIRONMENT');
INSERT INTO PRJ_MENUITEM (ID, NAME, URL, MENU_GROUP, MENU_ITEM_GROUP) VALUES (3, 'PROJECT_FSS', '/project/fss', 'ADMINISTRATION', 'ENVIRONMENT');

insert into acl_sid (id, principal, sid) values (100, FALSE, '/USER');
insert into acl_sid (id, principal, sid) values (101, FALSE, '/USER/ADMIN');
insert into acl_class (id, class) values (100, 'com.yqboots.project.menu.core.MenuItem');
-- -10005436 (hash code of '/project/menu')
insert into acl_object_identity (id, object_id_class, object_id_identity, parent_object, owner_sid, entries_inheriting) values (100, 100, -10005436, null, 101, FALSE);
insert into acl_entry (id, acl_object_identity, ace_order, sid, mask, granting, audit_success, audit_failure) values (100, 100, 1, 101, 1, TRUE, FALSE, FALSE);
-- -10270053 (hash code of '/project/dict')
insert into acl_object_identity (id, object_id_class, object_id_identity, parent_object, owner_sid, entries_inheriting) values (101, 100, -10270053, null, 101, FALSE);
insert into acl_entry (id, acl_object_identity, ace_order, sid, mask, granting, audit_success, audit_failure) values (101, 101, 1, 101, 1, TRUE, FALSE, FALSE);
-- 830954945 (hash code of '/project/fss')
insert into acl_object_identity (id, object_id_class, object_id_identity, parent_object, owner_sid, entries_inheriting) values (102, 100, 830954945, null, 101, FALSE);
insert into acl_entry (id, acl_object_identity, ace_order, sid, mask, granting, audit_success, audit_failure) values (102, 102, 1, 101, 1, TRUE, FALSE, FALSE);
