DELETE FROM SEC_USER_GROUPS WHERE USER_ID != 999;
DELETE FROM SEC_USER_ROLES WHERE USER_ID != 999;
DELETE FROM SEC_GROUP_ROLES WHERE GROUP_ID != 999;

DELETE FROM SEC_USER WHERE ID != 999;
DELETE FROM SEC_GROUP WHERE ID != 999;
DELETE FROM SEC_ROLE WHERE ID != 999;
