INSERT INTO SEC_USER (ID, USERNAME, PASSWORD, ENABLED) VALUES (3, 'user1', 'password', true);
INSERT INTO SEC_GROUP (ID, PATH, ALIAS, DESCRIPTION) VALUES (3, '/AGENTS', 'AGENTS', 'AGENTS');
INSERT INTO SEC_ROLE (ID, PATH, ALIAS, DESCRIPTION) VALUES (3, '/AGENTS', 'AGENTS', 'AGENTS');

INSERT INTO SEC_USER_GROUPS (USER_ID, GROUP_ID) VALUES (3, 1);
INSERT INTO SEC_USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 1);