INSERT INTO SEC_USER (ID, USERNAME, PASSWORD, ENABLED) VALUES (1, 'admin', 'password', true);
INSERT INTO SEC_USER (ID, USERNAME, PASSWORD, ENABLED) VALUES (2, 'user', 'password', true);

INSERT INTO SEC_GROUP (ID, PATH, ALIAS, DESCRIPTION) VALUES (1, '/ADMINS', 'ADMINS', 'ADMINS');
INSERT INTO SEC_GROUP (ID, PATH, ALIAS, DESCRIPTION) VALUES (2, '/USERS', 'USERS', 'USERS');

INSERT INTO SEC_ROLE (ID, PATH, ALIAS, DESCRIPTION) VALUES (1, '/ADMINS', 'ADMINS', 'ADMINS');
INSERT INTO SEC_ROLE (ID, PATH, ALIAS, DESCRIPTION) VALUES (2, '/USERS', 'USERS', 'USERS');

INSERT INTO SEC_USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO SEC_USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO SEC_USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);