INSERT INTO SEC_USER (ID, USERNAME, PASSWORD, ENABLED) VALUES (999, 'supervisor', 'password', true);

INSERT INTO SEC_GROUP (ID, PATH, ALIAS, DESCRIPTION) VALUES (999, '/SUPERVISOR', 'SUPERVISOR', 'SUPERVISOR');

INSERT INTO SEC_ROLE (ID, PATH, ALIAS, DESCRIPTION) VALUES (998, 'ROLE_USER', 'USER', 'USER');
INSERT INTO SEC_ROLE (ID, PATH, ALIAS, DESCRIPTION) VALUES (999, '/SUPERVISOR', 'SUPERVISOR', 'SUPERVISOR');

INSERT INTO SEC_USER_GROUPS (USER_ID, GROUP_ID) VALUES (999, 999);

INSERT INTO SEC_GROUP_ROLES (GROUP_ID, ROLE_ID) VALUES (999, 999);