CREATE TABLE acl_sid (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  principal BOOLEAN  NOT NULL,
  sid VARCHAR(100) NOT NULL,
  UNIQUE KEY UN_ACL_SID_PRINCIPAL (sid, principal)
) ENGINE=InnoDB;

CREATE TABLE acl_class (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  class VARCHAR(100) NOT NULL,
  UNIQUE KEY UN_ACL_CLASS (class)
) ENGINE=InnoDB;

CREATE TABLE acl_object_identity (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  object_id_class BIGINT UNSIGNED NOT NULL,
  object_id_identity BIGINT NOT NULL,
  parent_object BIGINT UNSIGNED,
  owner_sid BIGINT UNSIGNED,
  entries_inheriting BOOLEAN  NOT NULL,
  UNIQUE KEY UN_ACL_CLASS_ID (object_id_class, object_id_identity),
  CONSTRAINT FK_ACL_OBJ_ID FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id),
  CONSTRAINT FK_ACL_CLASS FOREIGN KEY (object_id_class) REFERENCES acl_class (id),
  CONSTRAINT FK_ACL_SID FOREIGN KEY (owner_sid) REFERENCES acl_sid (id)
) ENGINE=InnoDB;

CREATE TABLE acl_entry (
  id BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  acl_object_identity BIGINT UNSIGNED  NOT NULL,
  ace_order INTEGER NOT NULL,
  sid BIGINT UNSIGNED NOT NULL,
  mask  INTEGER UNSIGNED NOT NULL,
  granting BOOLEAN NOT NULL,
  audit_success BOOLEAN NOT NULL,
  audit_failure BOOLEAN NOT NULL,
  UNIQUE KEY UK_ACL_OI_ORDER (acl_object_identity, ace_order),
  CONSTRAINT FK_ACL_ENTRY_OI FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity (id),
  CONSTRAINT FK_ACL_ENTRY_SID FOREIGN KEY (sid) REFERENCES acl_sid (id)
) ENGINE=InnoDB;